-- Migration 20260522000001 — customer_year_recaps table.
--
-- Year-in-Strains Wrapped (PLAN_STRAIN_TREE_INNOVATION_2026_05_21 §C1).
-- One row per customer per calendar year. Populated by the mid-December
-- cron from the receipt-verified purchase corpus + strain-reviews data
-- once Phase 1 lands.
--
-- This file lives in the customer-site repo (NOT the inv-App auto-
-- applied migrations directory) because Doug runs it manually against
-- the shared Neon DB after Phase 1 ships. Phase 1 will likely promote
-- this DDL into the inv-App sequence-numbered migrations folder as
-- 03NN_wrapped_recap.sql for normal CI application.
--
-- Idempotent — guards everything with IF NOT EXISTS so re-running is
-- safe.

CREATE TABLE IF NOT EXISTS customer_year_recaps (
  id TEXT PRIMARY KEY,
  customer_id TEXT NOT NULL,
  year INTEGER NOT NULL,
  -- Ordered list of top strain slugs (3-10 entries typical). Stored as
  -- JSONB so we can later attach per-strain visit counts + family slug
  -- without a schema change.
  top_strain_slugs JSONB NOT NULL DEFAULT '[]'::jsonb,
  top_family_slug TEXT,
  -- Single dominant terpene slug ("limonene" / "myrcene" / "pinene" /
  -- "caryophyllene" / etc.). The descriptive note + label is rendered
  -- at read time from a SSoT in lib/wrapped.ts — keeps the column
  -- compact + lets us tune the prose without a DB rewrite.
  dominant_terpene TEXT,
  total_purchases INTEGER NOT NULL DEFAULT 0,
  total_strains_tried INTEGER NOT NULL DEFAULT 0,
  -- 1-sentence celebratory blurb. WAC 314-55-155 — generated by us, not
  -- by customer input, so the compliance check happens once at write
  -- time. Hard cap 500 chars at app layer; constraint left soft here
  -- to keep the schema portable.
  hero_blurb TEXT NOT NULL DEFAULT '',
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  opt_in_public BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'customer_year_recaps_unique'
  ) THEN
    ALTER TABLE customer_year_recaps
      ADD CONSTRAINT customer_year_recaps_unique
      UNIQUE (customer_id, year);
  END IF;
END $$;

-- Read path: by customer_id ordered by year DESC for the in-app history
-- chip (future "view past years" surface).
CREATE INDEX IF NOT EXISTS customer_year_recaps_customer_idx
  ON customer_year_recaps (customer_id, year DESC);

-- Public-share path: only opt-in rows surface at /u/<handle>/wrapped/YYYY.
CREATE INDEX IF NOT EXISTS customer_year_recaps_public_idx
  ON customer_year_recaps (year, customer_id)
  WHERE opt_in_public = TRUE;
