// Build identity exposed in the footer so Doug can verify a deploy landed.
// Bump BUILD_VERSION manually for major UX/feature changes; the short SHA
// comes from Vercel automatically on every deploy and is the authoritative
// "did my push actually land" signal.

// 4.235 — `lib/order-confirmation-email.ts` + `lib/welcome-email.ts` opt-out mailto switched from hardcoded `hi@seattlecannabis.co` to `RESEND_REPLY_TO ?? STORE.email`. Mirror of greenlife-web v3.335. Pre-fix the customer-facing footer pointed at `hi@` (the FROM address used by RESEND_FROM_SEATTLE), but the confirmed monitored Seattle inbox per `project_seattle_rainier_email_monitored` memory is `rainier@seattlecannabis.co`. RESEND_REPLY_TO is unset on Seattle so falls through to STORE.email = rainier@. Customer opt-out replies now reach the monitored inbox. 2 files / 6 lines changed (3 hardcoded refs per file). tsc clean.
// 4.230 — `lib/sms.ts` upgraded to inventoryapp's `normalizeToE164` boundary pattern (companion to inventoryapp v50.345 + greenlife-web v3.330). Pre-fix: `sendSms()` passed raw `to` straight to Twilio without normalization; the existing `normalizePhone` was simplistic (only handled `+`-prefix and naive 10-digit). Post-fix: new `normalizeToE164(input)` handles raw 10-digit, formatted `(509) 555-0100`, already-E.164, 11-digit `1XXX`, 11+-digit international, empty/short input. `sendSms()` calls it at the boundary so callers don't have to. `normalizePhone` kept as back-compat alias (E.164 round-trips unchanged). Single-file +35 LOC. tsc clean. Closes the SMS-helper drift between the inventoryapp + the two public sites flagged by `feedback_sms_e164_normalize_at_boundary`.
// 4.225 — `lib/email.ts` honors `RESEND_REPLY_TO` env var. Helper-side mirror of greenlife-web v3.325. Behavior unchanged on this project (`RESEND_REPLY_TO` not set, since `rainier@seattlecannabis.co` is actively monitored — replies default to From and land where they should). Helper kept symmetric across both repos so future routing changes stay env-only, no code edits.
// 4.220 — `/menu` server-side Dutchie prewarm. New `prewarmDutchieMenu()` async helper inside `app/menu/page.tsx` does a fire-alongside `fetch("https://api.iheartjane.com/api/v1/stores/5295/menu_products?per_page=1")` at SSR time, BEFORE the HTML response reaches the browser. Boost (which runs `afterInteractive` in `JaneMenu.tsx`) then queries the same URL ~200ms after page paint and hits Jane's now-warm edge cache — Dutchie cold-start time is amortized away from the customer's first paint. AbortSignal 1.5s timeout caps TTFB impact when Jane is unreachable; failure silently swallowed. Closes the customer-reported "menu error coming up first pass" pattern. Mirror of greenlife-web v3.320.
// 4.215 — `/api/health` exposes `emailConfigured: boolean` for one-curl Resend wire-up verification. After adding `RESEND_API_KEY` env var to a Vercel project, this flag flips `true` on the next deploy. Boolean only — never the key value. Mirror of greenlife-web v3.315.
// 4.211 — vendor-ads `daily_impression_cap` render-side enforcement (companion to inventoryapp v49.705 + migration 0158). `getActiveVendorAds()` now (1) excludes any ad whose TODAY's count has already hit cap via WHERE branch — `last_impression_day IS DISTINCT FROM today OR impressions_today < cap`, (2) atomic post-SELECT UPDATE increments `impressions_today` (or resets to 1 if day rolled over). Day boundary in `America/Los_Angeles` so rollover lines up with Kat's calendar. Lazy-reset semantics — no daily cron required. UPDATE failure swallowed. Mirror of greenlife-web v3.311.
// 4.200 — `/api/health` redacts Neon endpoint ID from `db.host`. Pre-fix exposed `ep-fragrant-hat-anugd8t6-pooler.c-6.us-east-1.aws.neon.tech` to anonymous health-check callers — the leading label uniquely identifies the Neon project. Now redacts to `***.c-6.us-east-1.aws.neon.tech` — keeps cluster/region/provider for ops "is this Neon? right region?" debug, drops project-uniqueness leak. Same fix on greenlife-web v3.305 + inventoryapp v49.045. Auth'd ops reading raw env var still see full hostname.
// 4.195 — VendorAdSlot wired to 4 remaining placement slots: homepage_top (above hero), homepage_under_brands (below brands carousel), menu_sidebar (above iHeartJane Boost embed on /menu), brand_page_top (top of /brands/[slug] generic template). All slots silent until admin curates active ads at inventoryapp /admin/marketing/vendor-ads. Now 5 of 5 schema-enum slots are mounted. Mirror on greenlife-web v3.295.
// 4.190 — `/brands` redirect FINAL FIX in `proxy.ts` middleware. v4.175's page-level approach (`permanentRedirect()` + `dynamic = "force-dynamic"`) deployed but did NOT produce a real HTTP 308 — Next 16 served HTTP 200 with homepage HTML body even though page was rendered dynamically (no `x-vercel-cache: HIT`). Middleware-level intercept runs BEFORE Next's render pipeline; response is a guaranteed real HTTP 308 with `location: /menu`. Page-level fallback in `app/brands/page.tsx` remains as defense-in-depth. Closes the `🟡 /brands redirect caveat` flag in LIVE.md. Mirror on greenlife-web v3.290.
// 4.180 — `/brands` redirect moved to proxy.ts middleware (FIRST attempt — see v4.190 for the actual ship). Note: this entry rode along with the HOTFIX commit `bf55ebc` that pinned vercel CLI to 52.0.0; the proxy.ts middleware change was intended but not yet present, so the page-level v4.175 approach remained the deployed behavior. Kept here as historical narrative.
// 4.175 — `/brands` redirect SEO fix. Was returning HTTP 200 + a Next.js Loading-then-`router.push("/menu")` static payload (Next 16 captures `redirect()` during prerender as static HTML when there's no `dynamic = "force-dynamic"` directive on the page). Crawlers + uptime checks + curl saw 200 + empty body, not a redirect. Now: `export const dynamic = "force-dynamic"` forces per-request render, and `redirect` swapped for `permanentRedirect` so the response is a real HTTP 308 → /menu (matches the page comment's stated intent + the LIVE.md follow-up note). Mirror on greenlife-web v3.265.
// 4.170 — Homepage 🆕 Just In section. New `getJustInProducts(12)` lib fn pulls products first stocked in last 7 days, currently in stock, brand-with-recent-sales gate. Renders above the disabled Today's Picks block as a 4-column indigo-themed grid with "🆕 New" pill on each card. CTA → /menu (Boost embed in prod). Mirror on greenlife-web v3.260.
// 4.165 — `getFeaturedProducts()` reads curated mode first. When admin (Kat/Doug) flips ON `is_featured` for any active product at inventoryapp /admin/marketing/featured (migration 0154), those products win the homepage carousel — sorted by `featured_priority DESC NULLS LAST, name ASC`. Falls back to the existing recent-`updated_at`-on-brands-with-sales auto-mode when zero curated. Companion to inventoryapp v44.x + greenlife-web v3.255.
// 4.160 — Homepage closure-aware. Adds `fetchClosureStatus()` to the page-level `Promise.all` and threads `closure.isClosed` into the existing `const open = isOpenNow()` so all "Open Now / Closed" indicators flip to "Closed" when a manager has flipped the emergency-closure override — matching the reality of the store, not just configured weekly hours. Also renders `<ClosureBanner>` at the very top of the page (above the hero) inside an amber strip for explicit reason context. Closure-aware customer surfaces now: `/` (v4.160) + `/menu` (v4.150) + `/order` (v4.140) + `/visit` (v4.155). Mirror on greenlife-web v3.250.
// 4.155 — `/visit` closure banner. Extends v4.150 to the third high-traffic customer entry point: the visit-info page (hours + directions + parking) where pre-drive customers land. Server Component made async to call `fetchClosureStatus()` server-side; banner renders above the hero when closed (consistent with /menu placement). Page already has `revalidate = 300` 5-min ISR so the closure-status fetch happens at most once per 5min per region. Closure-aware customer surfaces now: /menu (v4.150) + /order (v4.140) + /visit (v4.155). Mirror on greenlife-web v3.245.
// 4.150 — `/menu` server-rendered closure banner. Extends v4.140's `/order` banner to the higher-traffic `/menu` (iHeartJane Boost embed) entry point. New `<ClosureBanner>` component (presentational, used by both `/menu` server-side + `/order` client-side via prop). `/menu` page.tsx now does `Promise.all([getActiveDeals, fetchClosureStatus])` server-side; banner renders above the heading + JaneMenu when closed. ISR 60s on the page bounds the fetch frequency. Same graceful-degrade behavior — endpoint unreachable = banner doesn't render. Mirror on greenlife-web v3.240.
// 4.145 — `/brands` index deletion code lands (v4.135 changelog described this; that entry shipped via the closure-banner agent's bundle but the code edits were still uncommitted in working tree). This commit lands the actual file deletions + nav-strip + breadcrumb edits.
// 4.140 — `/order` block-on-closure banner. Fetches inventoryapp `/api/public/closure-status` on mount + before-submit re-check inside `placeOrder()`. When manager has flagged today closed via `/admin/hours-override`, surfaces an amber banner with the reason text, disables the Place Order button (label flips to "Closed today"), and the before-submit guard prevents a stale-state race. New `lib/closure-status.ts` helper wraps the fetch with a 5s AbortController timeout + always returns `{isClosed:false}` on any error path so a flaky endpoint never silently blocks ordering during normal hours. Default endpoint base = `seattle-cannabis-co.vercel.app`, overridable via `NEXT_PUBLIC_INVENTORYAPP_URL` (https-only). Closes the visibility chain queued in claude-loop-grinder Batch A items 1+2 (admin override v9.395 → public endpoint v9.745 → public-site banner now). Mirror on greenlife-web v3.230.
// 4.135 — `/brands` index page deleted (Doug + Kat call 2026-05-04). Even after the v4.101/v4.107/v4.119/v4.125 filter chain locked the data down to "products we currently carry + sold within 365 days," Kat's reasons for deletion were structural, not data-quality: (a) the page exposed our full vendor relationship list to outsiders; (b) it made daily-deal vendor concentration glanceable. Boutique `/brands/[slug]` overrides KEPT — they pull SEO traffic for "NWCS Seattle" / "Mfused Rainier" etc. queries. **Touched:** index → 308 redirect to `/menu`; SiteHeader nav, SiteFooter, home `Top Brands` section (kept section but stripped index-link affordances), about + visit page mesh tiles, not-found suggestion list, sitemap, llms.txt + llms-full.txt, vendor-access thanks page, blog post body. **`/brands/[slug]` template:** dropped "← All Brands" footer backlink + dropped "All Brands /" top-of-hero breadcrumb + dropped the "Brands" rung from the BreadcrumbList JSON-LD. Per-brand override components (NWCS, Mfused, Avitas, etc.) intentionally NOT touched. Mirror on greenlife-web v3.225.
// 4.125 — Brand-leakage round 3 — sales-history gate extended to product surfaces (/order, /shop, /stash, home featured carousel, home category previews, brand-products grid). Round 2 (v4.119) only gated brand pages; products from leaked brands could still appear on /menu+/order+/shop because those don't go through getActiveBrands/getBrandBySlug. Now `getMenuProducts` + `getProductsByIds` + `getFeaturedProducts` (+ fallback) + `getCategoryPreviewProducts` + `getBrandProducts` all INNER JOIN `brands_with_recent_sales` (vendors with ≥1 sale_line_items.sold_at >= NOW() - INTERVAL '365 days'). Customer-facing product display surfaces uniformly gated. Mirror on greenlife-web v3.211.
// 4.119 — Brand-leakage round 2 — sales-history gate (Doug screenshot 2026-05-04: "ABS Buds" Wenatchee-era brand rendering on Seattle with 13 FOG concentrate SKUs and "13 products in Seattle, WA" hero). Root cause: Seattle's Neon has leaked inventory_snapshots from a seed migration; v4.107 qty>0 alone couldn't distinguish "real Seattle inventory" from "ghost from a Wenatchee-seeded product." `getActiveBrands` + `getBrandBySlug` now INNER JOIN `brands_with_recent_sales` CTE that picks vendor_ids with ≥1 `sale_line_items.sold_at >= NOW() - INTERVAL '365 days'` row. Brands with no tail sale at THIS store get hidden from /brands index AND 404 on direct `/brands/[slug]` (so hand-authored Wenatchee-only override components don't render either). Mirror on greenlife-web v3.205.
// 4.113 — `proxy.ts` /api/health exemption broadened from exact-equality to `startsWith("/api/health")` so the cheap second-bucket /api/health/ping liveness endpoint also stays reachable on apex / per-deployment Vercel URLs. Pre-fix: /api/health was already exempt but /api/health/ping was still 308'ing — uptime monitors hitting /ping every 30-60s for second-bucket liveness couldn't follow the redirect cleanly. Same fix on greenlife-web v3.199.
// 4.107 — Brand pages + featured + category previews now require current inventory (Doug bug report 2026-05-04 "showing items we hant had in a long time on both stores"). Layers on top of v4.101/v4.102 carry_status tightening. Now `getActiveBrands` + `getBrandBySlug` + `getBrandProducts` + `getFeaturedProducts` (+ fallback) + `getCategoryPreviewProducts` all join the canonical `latest_inv` CTE and filter `li.qty > 0`. Customer no longer sees brands that haven't shipped a SKU in months, or "featured" products with empty shelves. WSLCB advertising-accuracy + customer-trust fix. Mirror on greenlife-web v3.187.
// 4.102 — `/order` + `/shop` + `/stash` product filter tightened (Doug bug report 2026-05-04 "saying we have things that we dont"). `getMenuProducts` + `getProductsByIds` in `lib/db.ts` now require strict `carry_status = 'active'` AND INNER JOIN to a latest-snapshot `qty > 0` CTE. Pairs with v4.101 brand-page tightening: same root cause, different surfaces. Mirror on greenlife-web v3.182.
// 4.101 — `/brands/[slug]` + `/brands` tightened product filter (Kat bug report 2026-05-04). `getActiveBrands` + `getBrandBySlug` + `getBrandProducts` in `lib/db.ts` now require `carry_status = 'active' AND unit_price > 0` instead of the looser `carry_status != 'discontinued'`. Kat: Bon Bombs were rendering on the Seattle brands page despite never having been carried in Seattle; samples were rendering on both stores. The looser filter let phasing-out vendors + $0-priced placeholder rows through. Same change shipped to greenlife-web v3.181. SQL stays one query each, no N+1 introduced.
// 4.96 — Apply form `?position=` deep-link support — when /careers links to /apply?position={id}, form fetches position from inventoryapp API, pre-selects role + shows 'Applying for: {title}' pill at top. Hidden positionId field passes the link to /api/applications. Silent fallback when fetch fails or position no longer open.
// 4.91 — Public /careers landing (Hiring Phase 5). Fetches open positions from inventoryapp /api/positions/open?store=seattle with 5-min ISR + 5s fetch timeout (falls back to "we keep good resumes on file" empty state on any failure). Position cards: title, store badges, pay-range/hours-pattern chips, safe-markdown description (XSS-safe — paragraphs/bullets/**bold** only, no HTML pass-through), "Apply for this role" CTA deep-linking /apply?position={id}. Hero leans on the "since 2010, on Rainier since 2018" heritage angle. Indigo/violet theme matching SCC chrome. Mirror on greenlife-web v3.171.
// 4.86 — Public /vendor-access self-serve form for brand partners (PLAN_VENDOR_ASSETS_PORTAL path B). Lands at /vendor-access — collects company + contact + email + phone + brand confirmation + intent — POSTs JSON to inventoryapp /api/vendor-access — feeds existing /admin/vendor-access-requests admin queue. Indexed (canonical), thanks page noindex. Free-text only — no file upload. Mirror page on greenlife-web v3.166.
// 4.81 — /brands/[slug] generic-template renders vendor-authored brand bio + Instagram/X/Facebook handles when filled in via /vmi/profile (inventoryapp). Section sits above the order CTA, only renders when at least one field is non-null. Handles are sanitized to /^[A-Za-z0-9._-]+$/ before being concatenated into URLs (prevents query-param injection or path traversal). Per-brand override components intentionally NOT touched — those are graduated, hand-authored layouts.
// 4.76 — /apply personality prompts: two optional written prompts (product-recommendation pitch + customer-recovery story) capture personality signal without the photo discrimination risk. Stored in applicants.metadata JSONB on inventoryapp side. Compliance: written-only — no photo (WA RCW 49.60 / EEOC pre-offer photo discrimination risk).
// 4.71 — Public /apply form: apply-to-work intake with resume upload + 3 references + 21+ confirmation. POSTs to inventoryapp /api/applications. Compliance: no photo / no SSN / no DOB.
export const BUILD_VERSION = "4.235";

export const BUILD_SHA = (
  process.env.VERCEL_GIT_COMMIT_SHA ??
  process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA ??
  "dev"
).slice(0, 7);
